[build]
  publish = "build"
  command = "npm ci && npm run build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  NODE_VERSION = "22.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 